config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'sessions#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount OkComputer::Engine, at: '/health'

  resources :summaries, :fines, :checkouts, only: [:index]
  resources :holds, only: [:index, :new, :create]
  resources :ill, only: [:new, :create]
  resources :redis_jobs, only: [:show, :destroy]

  patch '/holds/batch', to: 'holds#batch_update', as: :holds_batch_update
  delete '/holds/batch', to: 'holds#batch_destroy', as: :holds_batch_destroy
  patch '/checkouts/batch', to: 'checkouts#batch_update', as: :renewals_batch_update

  get 'accept-lending-policy', to: 'lending_policy#show', as: :lending_policy_show
  post 'accept-lending-policy', to: 'lending_policy#accept', as: :lending_policy_accept
  get 'accept-lending-policy/thank-you', to: 'lending_policy#thank_you', as: :lending_policy_thank_you
  get 'accept-lending-policy/error', to: 'lending_policy#error', as: :lending_policy_error

  get 'holds/all', to: 'holds#all', as: :holds_all
  get 'holds/result', to: 'holds#result', as: :result
  get 'ill/result', to: 'ill#result', as: :ill_result
  get 'checkouts/all', to: 'checkouts#all', as: :checkouts_all
  get '/logout', to: 'sessions#destroy', as: :logout
  match 'checkouts/export_ill_ris', to: 'checkouts#export_ill_ris', via: [:get, :post], as: 'export_ill_ris'
  get 'checkouts/export_ill_checkouts_email', to: 'checkouts#export_ill_checkouts_email',
                                              as: 'export_ill_checkouts_email'
  get 'checkouts/export_checkouts_email', to: 'checkouts#export_checkouts_email', as: 'export_checkouts_email'

  # error pages
  match 'user_not_found', to: 'errors#user_not_found', via: :all
  match '404', to: 'errors#not_found', via: :all
  match '422', to: 'errors#not_found', via: :all
  match '500', to: 'errors#internal_server_error', via: :all

  # catchall for not predefined requests - keep this at the very bottom of the routes file
  match '*catch_unknown_routes', to: 'errors#not_found', via: :all
end

app/models/hold.rb
# frozen_string_literal: true

# Model for holds in Symphony
class Hold
  include BibRecord

  PICKUP_LOCATION_REQUESTED = Settings.pickup_locations.to_h.invert
  PICKUP_LOCATION_ACTUAL = Settings.pickup_locations_actual.to_h

  attr_reader :record

  def initialize(record)
    @record = record
  end

  def key
    record['key']
  end

  def patron_key
    fields['patron']['key']
  end

  def ready_for_pickup?
    status_code == 'BEING_HELD'
  end

  def pickup_library_human
    PICKUP_LOCATION_ACTUAL[pickup_library_code.to_sym] || pickup_library_code
  end

  def expiration_date
    Time.zone.parse fields['expirationDate'] if fields['expirationDate']
  end

  def fill_by_date
    Time.zone.parse fields['fillByDate'] if fields['fillByDate']
  end

  def queue_position
    fields['queuePosition']
  end

  def suspend_begin_date
    Time.zone.parse fields['suspendBeginDate'] if fields['suspendBeginDate']
  end

  def suspend_end_date
    Time.zone.parse fields['suspendEndDate'] if fields['suspendEndDate']
  end

  def status_code
    fields['status']
  end

  private

    def fields
      record['fields']
    end

    def pickup_library_code
      fields.dig('pickupLibrary', 'key') || fields.dig('library', 'key') || 'NOTFOUND'
    end
end

app/controllers/holds_controller.rb
# frozen_string_literal: true

class HoldsController < ApplicationController
  before_action :set_cache_headers
  before_action :authenticate_user!
  before_action :patron_barred
  before_action :check_for_blanks!, only: :create
  before_action :unless_maintenance_mode, only: :new
  rescue_from NewHoldException, with: :deny_new
  rescue_from HoldCreateException, with: :deny_create

  # Render patron holds
  #
  # GET /holds
  def index
    @patron_key = current_user.patron_key
    @username = current_user.username
    ws_args = { patron_key: @patron_key, session_token: current_user.session_token }
    ViewHoldsJob.perform_later **ws_args
    ill_args = { webaccess_id: @username, type: :holds, library_key: patron.library_ill_path_key }
    ViewIlliadLoansJob.perform_later(**ill_args)

    render
  end

  # Handles form submission for changing holds in Symphony
  #
  # PATCH /holds
  # PUT /holds
  def batch_update
    params['hold_list']&.each do |hold_key|
      ws_args = { hold_key:, session_token: current_user.session_token }

      if params[:pickup_library].present?
        ChangePickupLibraryJob.perform_later **ws_args, pickup_library: params[:pickup_library]
      end

      if params[:pickup_by_date].present?
        ChangePickupByDateJob.perform_later **ws_args, pickup_by_date: params[:pickup_by_date]
      end
    end

    render plain: 'Update scheduled', status: :ok
  end

  # Prepares the form for creating a new hold
  #
  # GET /holds/new
  def new
    raise NewHoldException, 'Error' if params[:catkey].blank?

    form_builder = PlaceHoldForm::Builder.new(catkey: params[:catkey],
                                              user_token: current_user.session_token,
                                              client: symphony_client,
                                              library: patron.library)
    @place_hold_form_params = form_builder.generate

    raise NewHoldException, 'Error' if @place_hold_form_params.blank?
  end

  # Handles placing holds
  #
  # POST /holds
  def create
    PlaceHoldsJob.perform_later barcodes:,
                                session_token: current_user.session_token,
                                patron_key: current_user.patron_key,
                                catkey: params['catkey'],
                                pickup_library: params['pickup_library'],
                                pickup_by_date: params['pickup_by_date']

    redirect_to result_path
  end

  # Handles place hold response
  #
  # GET /holds/result
  def result
    if request.referer && URI(request.referer).path == '/holds/new'
      render
    else
      redirect_to '/not_found'
    end
  end

  # Handles form submission for canceling holds in Symphony
  #
  # DELETE /holds
  def batch_destroy
    params['hold_list']&.each do |hold_key|
      ws_args = { hold_key:, session_token: current_user.session_token }

      CancelHoldJob.perform_later(**ws_args)
    end

    render plain: 'Deletion scheduled', status: :ok
  end

  private

    def check_for_blanks!
      return unless barcodes.blank? || params['pickup_library'].blank? || params['pickup_by_date'].blank?

      raise HoldCreateException, 'Error'
    end

    def deny_new
      flash[:error] = if params['catkey'].blank?
                        t 'myaccount.hold.new_hold.catkey_missing'
                      else
                        t 'myaccount.hold.new_hold.error_html'
                      end

      redirect_to summaries_path
    end

    def deny_create
      flash[:error] = if barcodes.blank?
                        t 'myaccount.hold.place_hold.select_volumes'
                      elsif params['pickup_library'].blank?
                        t 'myaccount.hold.place_hold.select_library'
                      else
                        t 'myaccount.hold.place_hold.select_date'
                      end

      redirect_to new_hold_path(catkey: params[:catkey])
    end

    def barcodes
      [params['barcodes']].flatten.compact
    end
end

app/helpers/holds_helper.rb
# frozen_string_literal: true

module HoldsHelper
  def render_queue_position(hold)
    return hold.queue_position.ordinalize unless hold.queue_position.nil?

    'Unknown'
  end

  def render_hold_date(hold, date_field:)
    return l(hold.send(date_field), format: :short) if hold.send(date_field)

    'Never expires'
  end

  def render_status(hold)
    case hold.status_code
    when 'SUSPENDED'
      pretext = tag.em 'Suspended from'
      unless hold.suspend_end_date.nil?
        return pretext + ": #{l(hold.suspend_begin_date, format: :short)} - #{l(hold.suspend_end_date, format: :short)}"
      end

      'Inactive'
    else
      'Active'
    end
  end

  def render_pickup_libraries(selected)
    pickup_libraries = Hold::PICKUP_LOCATION_REQUESTED

    if selected.blank? || !pickup_libraries.value?(selected.to_sym)
      selected = ''
      default_choice = t('myaccount.hold.update_pickup.pickup_choose_text')
      pickup_libraries = { default_choice => '' }.merge(Hold::PICKUP_LOCATION_REQUESTED)
    end

    options_for_select(pickup_libraries, disabled: '', selected:)
  end

  def default_pickup_by_date(make_default: false)
    return '' unless make_default

    DateTime.now.+(14.days).strftime('%Y-%m-%d')
  end

  def minimum_pickup_by_date
    DateTime.now.strftime('%Y-%m-%d')
  end
end

app/views/holds/_form_inputs.html.erb
<%= label_tag :pickup_library, 'Pickup at:' %>
<%= select_tag 'pickup_library', render_pickup_libraries(selected),
               class: 'custom-select', data: 'pickup-location', required: validate_pickup_info %>

<%= render PlaceHoldDateComponent.new make_default: make_default, validate_pickup_info: validate_pickup_info, is_ill: is_ill %>

app/views/holds/_holds_not_ready_table.html.erb
<%= form_with url: holds_batch_destroy_path, method: :delete, id: 'pending-holds' do %>
  <table class="table table-responsive-sm">
    <caption><h2>Holds that are not ready for pickup</h2></caption>
    <thead class="border-top">

    <tr>
      <th scope="col">
        <%= render SelectAllComponent.new target_keyword: 'pending' %>
      </th>
      <th scope="col">Item</th>
      <th scope="col">Position in queue</th>
      <th scope="col">Pickup at</th>
      <th scope="col">Pick up by</th>
      <th scope="col">Status</th>
    </tr>
    </thead>

    <tbody>
    <% holds_not_ready.each do |hold| %>
      <tr id="hold<%= hold.key %>">
        <td>
          <%= render SelectAllChildComponent.new key: hold.key, target_keyword: 'pending', name: 'hold_list[]' %>
        </td>
        <td class="bibitem">
          <%= render BibItemComponent.new bibitem: hold %>
        </td>
        <td><%= render_queue_position hold %></td>
        <td class="pickup_at"><span><%= hold.pickup_library_human %></span></td>
        <td class="pickup-by"><span><%= render_hold_date hold, date_field: 'fill_by_date' %></span></td>
        <td class="hold_status"><span><%= render_status hold %></span></td>
      </tr>
    <% end %>
    </tbody>

  </table>
  <% unless Settings.maintenance_mode -%>
    <div class="row">
      <div class="col-12 col-lg-10">
        <div class="card">
          <h3 class="card-header">What to do with selected holds</h3>
          <div class="row">
            <div class="col-8">
              <div class="card-body">
                <h4>Edit Selected Holds</h4>
                <%= render partial: 'holds/form_inputs', locals: { selected: '',
                                                                   validate_pickup_info: false,
                                                                   make_default: false,
                                                                   is_ill: false } %>
                <br>
                  <%= submit_tag('Update Selected Holds', class: 'btn btn-primary deflatten', formmethod: 'PATCH', data: { disable_with: 'Please wait...' }) %>
              </div>
            </div>
            <div class="col-4 border-left">
              <div class="card-body">
                <h4 class="card-title">Cancel Selected Holds</h4>
                  <%= submit_tag('Cancel', class: 'btn btn-danger deflatten') %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end -%>
<% end %>

app/views/holds/_holds_ready_table.html.erb
<%= form_with url: holds_batch_destroy_path, method: :delete, id: 'active-holds' do %>
  <table class="table table-responsive-sm">
    <caption><h2>Holds that are ready for pickup</h2></caption>
    <thead class="border-top">
    <tr>
      <th scope="col"><%= render SelectAllComponent.new target_keyword: 'ready' %></th>
      <th scope="col">Item</th>
      <th scope="col">Pickup at</th>
      <th scope="col">Expires</th>
    </tr>
    </thead>
    <tbody>
    <% holds_ready.each do |hold| %>
      <tr id="hold<%= hold.key %>">
        <td>
          <%= render SelectAllChildComponent.new key: hold.key, target_keyword: 'ready', name: 'hold_list[]' %>
        </td>
        <td class="bibitem">
          <%= render BibItemComponent.new bibitem: hold %>
        </td>
        <td><%= hold.pickup_library_human %></td>
        <td class="hold_status"><%= render_hold_date hold, date_field: 'expiration_date' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% unless Settings.maintenance_mode -%>
    <%= submit_tag('Cancel Selected Holds', class: 'btn btn-danger deflatten') %>
  <% end %>
<% end %>

app/views/holds/_results.html.erb
<% if place_hold_results[:error].present? %>
    <div class="card bg-transparent my-3">
      <div class="card-header bg-transparent">
        <h3><%= pluralize place_hold_results[:error].length, 'Hold' %> Failed</h3>
      </div>
      <ul class="list-group list-group-flush">
        <% place_hold_results[:error].each do |result| %>
            <%= render PlaceHoldErrorComponent.new result: result, bib: result[:failed_hold] %>
        <% end %>
      </ul>
      <div class="card-footer bg-transparent">
        <p class="text-secondary"><%= t('myaccount.hold.place_hold.error_html') %></p>
      </div>
    </div>
<% end %>

<br>

<% if place_hold_results[:success].present? %>
    <div class="card bg-transparent my-3">
      <div class="card-header bg-transparent">
        <h3> <%= pluralize place_hold_results[:success].length, 'Hold' %> Placed </h3>
      </div>
      <ul class="list-group list-group-flush">
        <% place_hold_results[:success].each do |result| %>
            <%= render PlaceHoldSuccessComponent.new result: result %>
        <% end %>
      </ul>
      <div class="card-footer bg-transparent">
        <p class="text-secondary"><%= t('myaccount.hold.place_hold.success_html') %></p>
      </div>
    </div>
<% end %>

<br>

<%= link_to 'Back to Catalog',
            "https://catalog.libraries.psu.edu/catalog/#{place_hold_catkey}",
            class: 'btn btn-info' %>
<%= link_to t('myaccount.see_all_holds_button_text'), holds_path, class: 'btn btn-info' %>

app/views/holds/all.html.erb
<% if holds_ready.blank? && holds_not_ready.blank? %>
  <p>You have no holds at this time.</p>
<% else %>
  <% if holds_ready.present? %>
    <%= render partial: 'holds/holds_ready_table', locals: { holds_ready: holds_ready } %>
  <% else %>
    <p>You have no holds ready to be picked up at this time.</p>
  <% end %>
  <% if holds_not_ready.present? %>
    <%= render partial: 'holds/holds_not_ready_table', locals: { holds_not_ready: holds_not_ready } %>
  <% end %>

<% end %>

app/views/holds/ill.html.erb
<% if ill_holds.present? %>
  <table class="table table-responsive-sm">
    <caption><h2>Illiad Holds</h2></caption>
    <thead>

    <tr>
      <th scope="col">Item</th>
      <th scope="col">Author</th>
      <th scope="col">Creation Date</th>
      <th scope="col">Status</th>
    </tr>
    </thead>

    <tbody>
    <% ill_holds.each_with_index do |hold, i| %>
      <tr id="hold<%= i %>">
        <td id="title"><span><%= hold.title %></span></td>
        <td id="author"><span><%= hold.author %></span></td>
        <td id="creation-date"><span><%= render_hold_date hold, date_field: 'creation_date' %></span></td>
        <td id="status"><span><%= hold.status %></span></td>
      </tr>
    <% end %>
    </tbody>

  </table>
<% end %>

app/views/holds/ill_holds.html.erb
<% if illiad_loans.present? %>
  <table class="table table-responsive-sm">
    <div class="row mb-3">
      <div class="col-auto pe-0">
        <h1>Interlibrary Loan Requests</h1>
      </div>
      <div class="col-auto ps-2">
        <p class="mt-2">
          (<a href="<%= ill_manage_link(library_key) %>">Manage your Interlibrary Loan Requests</a>)
        </p>
      </div>
    </div>
    <thead class="border-top">

    <tr>
      <th scope="col">Item</th>
      <th scope="col">Author</th>
      <th scope="col">Creation Date</th>
      <th scope="col">Status</th>
    </tr>
    </thead>

    <tbody>
    <% illiad_loans.each_with_index do |hold, i| %>
      <tr id="hold-<%= i %>">
        <td id="title-<%= i %>"><span><%= hold.title %></span></td>
        <td id="author-<%= i %>"><span><%= hold.author %></span></td>
        <td id="creation-date-<%= i %>"><span><%= render_hold_date hold, date_field: 'creation_date' %></span></td>
        <td id="status-<%= i %>"><span><%= hold.status %></span></td>
      </tr>
    <% end %>
    </tbody>

  </table>
<% end %>

app/views/holds/index.html.erb
<div class="load-ill-holds" data-username="<%= @username %>">
  <p class="m-5 text-center">
    <span class="spinner-border" role="status">
      <span class="sr-only">Loading...</span>
    </span>
    <%= t('myaccount.loading_html') %>
  </p>
</div>

<h1>Holds</h1>
<p><%= t('myaccount.holds_info_html') %></p>

<div class="load-holds" data-patron-key="<%= @patron_key %>">
  <p class="m-5 text-center">
    <span class="spinner-border" role="status">
      <span class="sr-only">Loading...</span>
    </span>
    <%= t('myaccount.loading_html') %>
  </p>
</div>

app/views/holds/new.html.erb
<h1>A Hold Will Be Placed For You</h1>

<p>
  <%= render GenericValueWithLabelComponent.new label: 'Title', value: @place_hold_form_params[:title] %> <br>
  <%= render GenericValueWithLabelComponent.new label: 'Author', value: @place_hold_form_params[:author] %>
</p>

<%= form_with url: '/holds', local: true, method: :post do %>
  <%= render PlaceHoldHiddenInputComponent.new(barcode: @place_hold_form_params[:barcode]) %>
  <%= hidden_field_tag :catkey, params[:catkey] %>
  <%= render partial: 'holds/form_inputs', locals: { selected: @place_hold_form_params[:pickup_library],
                                                     validate_pickup_info: true,
                                                     make_default: true,
                                                     is_ill: false } %>
  <%= render PlaceHoldCheckboxWrapperComponent.new volumetric_calls: @place_hold_form_params[:volumetric_calls] %>
  <% if @patron.ill_ineligible? %>
    <p> A local copy isn't available. You can select 'Place Hold' to join the holds list for when one is returned.
    <br>Also consider checking at your local library or asking if they can get a copy for you through Interlibrary Loan. </p>
<% end %>
  <%= submit_tag('Place Hold', class: 'btn btn-info') %>
  <%= link_to 'Cancel', Rails.application.config.catalog_url + @place_hold_form_params[:catkey], class: 'btn btn-danger' %>
<% end %>

app/views/holds/result.html.erb
<h1>Results of Hold Request for <%= patron.display_name %></h1>

<div class="load-requested-holds" data-patron-key="<%= patron.key %>">
  <p class="m-5 text-center"><span class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </span> Attempting to place holds, please wait...</p>
</div>