config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'sessions#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount OkComputer::Engine, at: '/health'

  resources :summaries, :fines, :checkouts, only: [:index]
  resources :holds, only: [:index, :new, :create]
  resources :ill, only: [:new, :create]
  resources :redis_jobs, only: [:show, :destroy]

  patch '/holds/batch', to: 'holds#batch_update', as: :holds_batch_update
  delete '/holds/batch', to: 'holds#batch_destroy', as: :holds_batch_destroy
  patch '/checkouts/batch', to: 'checkouts#batch_update', as: :renewals_batch_update

  get 'accept-lending-policy', to: 'lending_policy#show', as: :lending_policy_show
  post 'accept-lending-policy', to: 'lending_policy#accept', as: :lending_policy_accept
  get 'accept-lending-policy/thank-you', to: 'lending_policy#thank_you', as: :lending_policy_thank_you
  get 'accept-lending-policy/error', to: 'lending_policy#error', as: :lending_policy_error

  get 'holds/all', to: 'holds#all', as: :holds_all
  get 'holds/result', to: 'holds#result', as: :result
  get 'ill/result', to: 'ill#result', as: :ill_result
  get 'checkouts/all', to: 'checkouts#all', as: :checkouts_all
  get '/logout', to: 'sessions#destroy', as: :logout
  match 'checkouts/export_ill_ris', to: 'checkouts#export_ill_ris', via: [:get, :post], as: 'export_ill_ris'
  get 'checkouts/export_ill_checkouts_email', to: 'checkouts#export_ill_checkouts_email',
                                              as: 'export_ill_checkouts_email'
  get 'checkouts/export_checkouts_email', to: 'checkouts#export_checkouts_email', as: 'export_checkouts_email'

  # error pages
  match 'user_not_found', to: 'errors#user_not_found', via: :all
  match '404', to: 'errors#not_found', via: :all
  match '422', to: 'errors#not_found', via: :all
  match '500', to: 'errors#internal_server_error', via: :all

  # catchall for not predefined requests - keep this at the very bottom of the routes file
  match '*catch_unknown_routes', to: 'errors#not_found', via: :all
end

app/controllers/lending_policy_controller.rb
# frozen_string_literal: true

class LendingPolicyController < ApplicationController
  before_action :authenticate_user!

  def accept
    # even if the patron is not eligible for wage garnishment (already opted in or some other reason),
    # just redirect them to the thank you path to avoid further user confusion
    return redirect_to lending_policy_thank_you_path unless patron.eligible_for_wage_garnishment?

    client = SymphonyClient.new
    response = client.accept_lending_policy(patron:, session_token: current_user.session_token)
    if response.status == 200
      redirect_to lending_policy_thank_you_path
    else
      redirect_to lending_policy_error_path
    end
  end
end

app/views/lending_policy/error.html.erb
<h1>We're sorry, but something went wrong.</h1>

<p>Please try again or come back later if the error occurs again. You can also <%= link_to 'give us feedback', 'https://libraries.psu.edu/website-feedback' %> about the problem. </p>
<p> If you need more assistance, <%= link_to 'Ask a Librarian', 'https://libraries.psu.edu/ask/' %>.</p>

app/views/lending_policy/show.html.erb
<h1>Acceptance of University Libraries Lending Policy</h1>

<p>
  The University Libraries has revised its Lending Policy to include the following statement:
</p>

<p class="mx-5">
  "For lost materials, if payment is not received for replacement costs within 6 months from notification that the money is due at the Libraries, payment will be payroll deducted for current University employees. For all other fees, if payment is not received within 60 days, payment will be payroll deducted. Additional fees may be charged for this process."
</p>

<p>
  The Lending Policy can be seen in its entirety on the Pennsylvania State University Libraries Web Page at <a href="https://libraries.psu.edu/services/borrow-renew/borrowing-privileges">https://libraries.psu.edu/services/borrow-renew/borrowing-privileges</a>. The policy is subject to change without individual notice. Any change in borrower status or address should be reported to the Libraries immediately.
</p>

<p>
  By accepting these terms, the applicant agrees to the policies of the Pennsylvania State University Libraries. Please note that acceptance of this policy is necessary to maintain your borrowing privileges.
</p>

<hr class="my-4" />

<%= form_with url: lending_policy_accept_path, method: :post, id: 'accept-lending-policy-form', local: true do %>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="accept-lending-policy-checkbox">
    <label class="form-check-label" for="accept-lending-policy-checkbox">
      I authorize the Libraries, after appropriate notice, to deduct from my paycheck any fees incurred. Additional fees may be charged for this process. Upon acceptance of this policy, my borrowing privileges will be re-instated.
    </label>
  </div>

  <%= submit_tag('Accept & Continue', class: 'btn btn-primary', id: 'accept-lending-policy-submit', disabled: true) %>
<% end %>

app/views/lending_policy/thank_you.html.erb
<h1>Thank You</h1>

<p>Thank you for accepting the Libraries' Fee Policy.</p>