config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'sessions#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount OkComputer::Engine, at: '/health'

  resources :summaries, :fines, :checkouts, only: [:index]
  resources :holds, only: [:index, :new, :create]
  resources :ill, only: [:new, :create]
  resources :redis_jobs, only: [:show, :destroy]

  patch '/holds/batch', to: 'holds#batch_update', as: :holds_batch_update
  delete '/holds/batch', to: 'holds#batch_destroy', as: :holds_batch_destroy
  patch '/checkouts/batch', to: 'checkouts#batch_update', as: :renewals_batch_update

  get 'accept-lending-policy', to: 'lending_policy#show', as: :lending_policy_show
  post 'accept-lending-policy', to: 'lending_policy#accept', as: :lending_policy_accept
  get 'accept-lending-policy/thank-you', to: 'lending_policy#thank_you', as: :lending_policy_thank_you
  get 'accept-lending-policy/error', to: 'lending_policy#error', as: :lending_policy_error

  get 'holds/all', to: 'holds#all', as: :holds_all
  get 'holds/result', to: 'holds#result', as: :result
  get 'ill/result', to: 'ill#result', as: :ill_result
  get 'checkouts/all', to: 'checkouts#all', as: :checkouts_all
  get '/logout', to: 'sessions#destroy', as: :logout
  match 'checkouts/export_ill_ris', to: 'checkouts#export_ill_ris', via: [:get, :post], as: 'export_ill_ris'
  get 'checkouts/export_ill_checkouts_email', to: 'checkouts#export_ill_checkouts_email',
                                              as: 'export_ill_checkouts_email'
  get 'checkouts/export_checkouts_email', to: 'checkouts#export_checkouts_email', as: 'export_checkouts_email'

  # error pages
  match 'user_not_found', to: 'errors#user_not_found', via: :all
  match '404', to: 'errors#not_found', via: :all
  match '422', to: 'errors#not_found', via: :all
  match '500', to: 'errors#internal_server_error', via: :all

  # catchall for not predefined requests - keep this at the very bottom of the routes file
  match '*catch_unknown_routes', to: 'errors#not_found', via: :all
end

app/models/checkout.rb
# frozen_string_literal: true

# Model for the Checkouts page
class Checkout
  include BibRecord

  attr_reader :record

  def initialize(record)
    @record = record
  end

  def key
    record['key']
  end

  def status
    fields['status']
  end

  def status_human
    return '' unless overdue?

    claims_returned? ? 'Claims Returned' : 'Overdue'
  end

  def due_date
    fields['dueDate'] && Time.zone.parse(fields['dueDate'])
  end

  def due_date_human
    format_due_date due_date
  end

  def recall_due_date_human
    format_due_date recall_due_date
  end

  def recalled?
    recalled_date.present?
  end

  def claims_returned?
    claims_returned_date.present?
  end

  def overdue?
    fields['overdue']
  end

  def accrued
    fields.dig('estimatedOverdueAmount', 'amount').to_d
  end

  def renewal_count
    fields['renewalCount'] || 0
  end

  private

    def fields
      record['fields']
    end

    def recalled_date
      fields['recalledDate'] && Time.zone.parse(fields['recalledDate'])
    end

    def recall_due_date
      fields['recallDueDate'] && Time.zone.parse(fields['recallDueDate'])
    end

    def claims_returned_date
      fields['claimsReturnedDate'] && Time.zone.parse(fields['claimsReturnedDate'])
    end

    def format_due_date(date)
      return unless date

      return I18n.l(date, format: :long) unless I18n.l(date, format: :time_only) == '11:59pm'

      I18n.l(date, format: :short)
    end
end

app/controllers/checkouts_controller.rb
# frozen_string_literal: true

class CheckoutsController < ApplicationController
  include ActionView::Helpers::TagHelper

  before_action :set_cache_headers
  before_action :authenticate_user!

  # Render a list of checkouts and renewals for patron
  #
  # GET /checkouts
  def index
    @username = current_user.username
    ws_args = { patron_key: current_user.patron_key, session_token: current_user.session_token }
    ViewCheckoutsJob.perform_later **ws_args
    ill_args = { webaccess_id: @username, type: :checkouts, library_key: patron.library_ill_path_key }
    ViewIlliadLoansJob.perform_later(**ill_args)

    @patron_key = current_user.patron_key
    render
  end

  # Handles form submission for batch checkout renewal requests
  #
  # PATCH /checkouts/batch
  def batch_update
    checkouts_to_renew&.each do |checkout|
      ws_args = { resource: '/catalog/item',
                  item_key: checkout,
                  session_token: current_user.session_token }
      RenewCheckoutJob.perform_later(**ws_args)
    end

    render plain: 'Renew', status: :ok
  end

  def export_ill_ris
    ris_string = ''
    ill_checkouts = IlliadClient.new.send(:get_loan_checkouts, current_user.username)

    ill_checkouts.each_with_index do |checkout, _i|
      ris_string += tag_format('TY', checkout.type)
      ris_string += tag_format('TI', checkout.title)
      ris_string += tag_format('A1', checkout.author)
      ris_string += tag_format('PY', checkout.date)
      ris_string += tag_format('SN', checkout.identifier)
      ris_string += tag_format('Y2', Time.now.strftime('%Y-%m-%d'))
      ris_string += tag_format('ET', checkout.edition)
      ris_string += "ER  -\r\n"
    end

    send_data ris_string, filename: 'document.ris', type: :ris
  end

  def export_checkouts_email
    response = symphony_client.patron_info(patron_key: current_user.patron_key,
                                           session_token: current_user.session_token,
                                           item_details: { circRecordList: true })

    patron = Patron.new(response)

    checkouts = patron.checkouts.map do |c|
      {
        catkey: c.catkey,
        title: c.title,
        author: c.author,
        call_number: c.call_number
      }
    end

    begin
      CheckoutsMailer.export_checkouts(current_user.username, checkouts).deliver_now
      flash[:success] = I18n.t('myaccount.email.success')
    rescue StandardError
      flash[:error] = I18n.t('myaccount.email.error')
    end

    redirect_to '/checkouts'
  end

  def export_ill_checkouts_email
    ill_checkouts = []
    raw_ill_checkouts = IlliadClient.new.send(:get_loan_checkouts, current_user.username)
    raw_ill_checkouts.each do |checkout|
      checkout_data = {
        title: checkout.title,
        author: checkout.author,
        date: checkout.date,
        identifier: checkout.identifier
      }
      ill_checkouts.push(checkout_data)
    end

    begin
      CheckoutsMailer.export_ill_checkouts(current_user.username, ill_checkouts).deliver_now
      flash[:success] = I18n.t('myaccount.email.success')
    rescue StandardError
      flash[:error] = I18n.t('myaccount.email.error')
    end

    redirect_to '/checkouts'
  end

  private

    def checkouts_to_renew
      params['renewal_list']
    end

    def deny_access
      flash[:error] = 'An unexpected error has occurred'

      redirect_to checkouts_path
    end

    def tag_format(tag, value)
      return '' unless value

      "#{tag}  - #{value}\r\n"
    end
end

app/views/checkouts/_checkouts_table.html.erb
<%= form_with url: renewals_batch_update_path, method: :patch, id: 'checkouts' do %>
    <table id="checkouts-table" class="table table-responsive-sm" role="table" aria-live="polite">
      <caption>
        <span class="dropdown float-end">
          <style>
            .dropdown button,
            .dropdown-menu {
              font-family: "Open Sans", Arial, serif;
            }
          </style>
          <button
            class="btn btn-primary deflatten dropdown-toggle mb-2"
            type="button"
            id="export-checkouts-btn"
            data-bs-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">
            Export All Checkouts
          </button>
          <div class="dropdown-menu" aria-labelledby="export-checkouts-btn">
            <%= link_to 'RIS File', "#{Settings.catalog.bulk_ris_url}#{checkouts.map { |c| c.catkey.to_s }.join(',')}", class: 'dropdown-item' %>
            <%= link_to 'Email', export_checkouts_email_path, class: 'dropdown-item' %>
          </div>
        </span>
        <h2>Checkouts</h2>
      </caption>
      <thead class="border-top">
      <tr>
        <th scope="col">
          <%= render SelectAllComponent.new target_keyword: 'renewal' %>
        </th>
        <th scope="col">Item</th>
        <th scope="col">Times Renewed</th>
        <th scope="col">Due Date</th>
        <th scope="col">Status</th>
        <th scope="col">You Owe</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <td colspan="6">
          <% unless Settings.maintenance_mode -%>
            <%= submit_tag 'Renew',
                           class: 'btn btn-primary deflatten',
                           aria: { controls: 'checkouts-table' },
                           data: { disable_with: 'Please wait...' } %>
          <% end -%>
        </td>
      </tr>
      </tfoot>
      <tbody>
      <% checkouts.each do |checkout| %>
          <tr id="checkout<%= checkout.item_key %>">
            <td>
              <%= render SelectAllChildComponent.new key: checkout.item_key, target_keyword: 'renewal' %>
            </td>
            <td class="bibitem">
              <%= render BibItemComponent.new bibitem: checkout %>
            </td>
            <td class="renewal_count"><span><%= checkout.renewal_count if checkout.renewal_count.positive? %></span></td>
            <td class="due-date"><span><%= render partial: 'checkouts/due_date', locals: { checkout: checkout } %></span></td>
            <td class="status"><span><%= checkout.status_human %></span></td>
            <td><%= number_to_currency checkout.accrued if checkout.accrued.positive? %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/checkouts/_due_date.html.erb
<% if checkout.recalled? %>
  Recalled<br>
  <%= checkout.recall_due_date_human %><br>
<% end %>
<%= checkout.due_date_human -%>

app/views/checkouts/all.html.erb
<% if checkouts.length.positive? %>
    <p>
      <div class="ml-4">Total Checked Out: <%= checkouts.length %></div>

      <% count = checkouts.select(&:recalled?).length %>
      <% if count.positive? %>
          <div class="ml-4">Recalled: <%= count %></div>
      <% end %>

      <% count = checkouts.select(&:overdue?).length %>
      <% if count.positive? %>
          <div class="ml-4">Overdue: <%= count %></div>
      <% end %>
    </p>
    <%= render partial: 'checkouts/checkouts_table', locals: { checkouts: checkouts } %>
<% else %>
    <p>You have no checkouts at this time.</p>
<% end %>

app/views/checkouts/ill_checkouts.html.erb
<% if illiad_loans.present? %>
  <table class="table table-responsive-sm">
    <div class='row pl-3 pt-2 pb-3'>
      <h1>Interlibrary Loan Checkouts</h1>
      <p class='pl-2 pt-2'>
        (<a href="<%= ill_manage_link(library_key) %>">Manage your Interlibrary Loans</a>)
      </p>
      <span class="dropdown ml-auto">
        <button
          class="btn btn-primary deflatten dropdown-toggle mb-2"
          type="button"
          id="export-ill-checkouts-btn"
          data-bs-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
          Export All ILLiad Checkouts
        </button>
        <div class="dropdown-menu" aria-labelledby="export-ill-checkout-btn">
          <%= link_to 'RIS File', export_ill_ris_path, class: 'dropdown-item' %>
          <%= link_to 'Email', export_ill_checkouts_email_path, class: 'dropdown-item' %>
        </div>
      </span>
    </div>
    <thead class="border-top">

    <tr>
      <th scope="col">Item</th>
      <th scope="col">Author</th>
      <th scope="col">Due Date</th>
      <th scope="col">Status</th>
    </tr>
    </thead>

    <tbody>
    <% illiad_loans.each_with_index do |checkout, i| %>
      <tr id="checkout-<%= i %>">
        <td id="title-<%= i %>"><span><%= checkout.title %></span></td>
        <td id="author-<%= i %>"><span><%= checkout.author %></span></td>
        <td id="due-date-<%= i %>"><span><%= render_hold_date checkout, date_field: 'due_date' %></span></td>
        <td id="status-<%= i %>"><span><%= checkout.status %></span></td>
      </tr>
    <% end %>
    </tbody>

  </table>
<% end %>

app/views/checkouts/index.html.erb
<div class="load-ill-checkouts" data-username="<%= @username %>">
  <p class="m-5 text-center">
    <span class="spinner-border" role="status">
      <span class="sr-only">Loading...</span>
    </span>
    <%= t('myaccount.loading_html') %>
  </p>
</div>

<h1>Checkouts/Renewals</h1>
<p><%= t('myaccount.checkouts_info_html') %></p>

<div class="load-checkouts" data-patron-key="<%= @patron_key %>">
  <p class="m-5 text-center">
    <span class="spinner-border" role="status">
      <span class="sr-only">Loading...</span>
    </span>
    <%= t('myaccount.loading_html') %>
  </p>
</div>