config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'sessions#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount OkComputer::Engine, at: '/health'

  resources :summaries, :fines, :checkouts, only: [:index]
  resources :holds, only: [:index, :new, :create]
  resources :ill, only: [:new, :create]
  resources :redis_jobs, only: [:show, :destroy]

  patch '/holds/batch', to: 'holds#batch_update', as: :holds_batch_update
  delete '/holds/batch', to: 'holds#batch_destroy', as: :holds_batch_destroy
  patch '/checkouts/batch', to: 'checkouts#batch_update', as: :renewals_batch_update

  get 'accept-lending-policy', to: 'lending_policy#show', as: :lending_policy_show
  post 'accept-lending-policy', to: 'lending_policy#accept', as: :lending_policy_accept
  get 'accept-lending-policy/thank-you', to: 'lending_policy#thank_you', as: :lending_policy_thank_you
  get 'accept-lending-policy/error', to: 'lending_policy#error', as: :lending_policy_error

  get 'holds/all', to: 'holds#all', as: :holds_all
  get 'holds/result', to: 'holds#result', as: :result
  get 'ill/result', to: 'ill#result', as: :ill_result
  get 'checkouts/all', to: 'checkouts#all', as: :checkouts_all
  get '/logout', to: 'sessions#destroy', as: :logout
  match 'checkouts/export_ill_ris', to: 'checkouts#export_ill_ris', via: [:get, :post], as: 'export_ill_ris'
  get 'checkouts/export_ill_checkouts_email', to: 'checkouts#export_ill_checkouts_email',
                                              as: 'export_ill_checkouts_email'
  get 'checkouts/export_checkouts_email', to: 'checkouts#export_checkouts_email', as: 'export_checkouts_email'

  # error pages
  match 'user_not_found', to: 'errors#user_not_found', via: :all
  match '404', to: 'errors#not_found', via: :all
  match '422', to: 'errors#not_found', via: :all
  match '500', to: 'errors#internal_server_error', via: :all

  # catchall for not predefined requests - keep this at the very bottom of the routes file
  match '*catch_unknown_routes', to: 'errors#not_found', via: :all
end

app/views/layouts/_announcement.html.erb
<div class="announcement container-fluid <%= Settings.announcement&.html_class %>">
  <div class="row align-items-center">
    <div class="col align-content-center">
      <p class="text-center mt-2 mb-2 pb-1"><i class="fas <%= Settings.announcement&.icon %>"></i> <%= sanitize Settings.announcement&.message %></p>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto" role="contentinfo">
  <div class="container">
    <section class="row">
      <div class="col-md-2 footer__logo">
        <%= link_to image_pack_tag('static/packs/images/psu_mark_footer.png', alt: 'Penn State logo', class: 'img-fluid'), 'https://www.psu.edu', title: t('blacklight.organization_name').html_safe %>
      </div>

      <div class="col-md-4 footer__boiler">
        <p>Copyright @<%= current_year %> The Pennsylvania State University.
          All rights reserved. Except where otherwise noted, this work is subject to a <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 license.</a> <a href="https://libraries.psu.edu/psu-libraries-copyright-statement">Details and exceptions.</a></p>
        <p><a href="http://www.psu.edu/ur/legal.html">Legal Statements</a> | <a href="http://www.psu.edu/ur/hotline.html">PSU Hotlines</a></p>
      </div>

      <div class="col-md-4 footer__meta">
        <h2>Penn State<br>University Libraries</h2>
        <div class="row g-0">
          <div class="col">
            <ul class="w-100">
              <li><a href="https://libraries.psu.edu">Libraries Home</a></li>
              <li><a href="https://staff.libraries.psu.edu">Libraries Intranet (Staff Only)</a></li>
              <li><a href="https://libraries.psu.edu/accessibility-help"><i class="fab fa-accessible-icon"></i> Accessibility Help</a></li>
              <li><a href="https://libraries.psu.edu/website-feedback">Website Feedback</a></li>
              <li><a href="https://libraries.psu.edu/policies">Policies and Guidelines</a></li>
              <li><a href="https://libraries.psu.edu/directory">Staff Directory</a></li>
            </ul>
          </div>
          <div class="col">
            <ul class="w-100">
              <li><a href="tel:814-865-6368">(814) 865-6368</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-md-2 footer__social">
        <h2>Connect with<br>Penn State University Libraries</h2>
        <ul>
          <li><a href="https://www.facebook.com/psulibs"><i class="fab fa-facebook-square"></i> Facebook</a></li>
          <li><a href="https://twitter.com/psulibs"><i class="fab fa-twitter-square"></i> Twitter</a></li>
          <li><a href="https://www.instagram.com/psulibs/"><i class="fab fa-instagram"></i> Instagram</a></li>
        </ul>
      </div>

    </section>
  </div>
  <div class="ask" id="libchat_d51e38627705fc23934afaba4f563cc8"></div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Internet Explorer use the highest version available -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>My Account | Pennsylvania State University Libraries</title>

  <%= stylesheet_pack_tag 'application' %>
  <%= javascript_pack_tag 'application', defer: true %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= content_for(:head) %>

  <!-- Matomo -->
  <script>
    var _paq = window._paq = window._paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="https://analytics.libraries.psu.edu/matomo/";
      _paq.push(['setTrackerUrl', u+'matomo.php']);
      _paq.push(['setSiteId', <%= Settings.matomo_id %>]);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
  <!-- End Matomo Code -->

  <script src="https://psu.libanswers.com/load_chat.php?hash=d51e38627705fc23934afaba4f563cc8"></script>
</head>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light py-0" role="navigation">
  <div class="container">
    <button class="navbar-toggler my-2" type="button" data-bs-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav nav-pills nav-justified container pr-0 d-inline-block d-sm-flex">
        <%= render partial: 'shared/nav_link', locals: { name: 'Account Summary', path: summaries_path } %>
        <%= render partial: 'shared/nav_link', locals: { name: 'Checkouts/Renewals', path: checkouts_path } %>
        <%= render partial: 'shared/nav_link', locals: { name: 'Holds', path: holds_path } %>
        <%= render partial: 'shared/nav_link', locals: { name: 'Bills', path: fines_path } %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_top_bar.html.erb
<header class="navbar navbar-expand-md navbar-dark bg-dark" role="banner">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to image_pack_tag('static/packs/images/logo.png', alt: 'Penn State University Libraries logo', class: 'img-fluid'), 'https://libraries.psu.edu' %>
      <%= link_to 'MyAccount', root_path, class: 'site-title' %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="h-100">
  <%= render 'layouts/head' %>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/announcement' if Settings.show_announcement %>
    <%= render 'layouts/top_bar' %>
    <%= render 'layouts/navigation' %>

    <main id="main-container" class="container my-3" role="main">
      <div class="row">
        <div class="col-md-12">
          <%= render 'content/maintenance' if Settings.maintenance_mode %>
          <%= render partial: 'shared/flash_msg', layout: nil %>
          <%= yield %>
        </div>
      </div>
      <%= render 'content/user_util_links' %>
    </main>

    <%= render 'layouts/footer' %>

    <%= render 'shared/session_expiry_modal' %>

    <div aria-live="polite" aria-atomic="true">
      <div class="toast-insertion-point" style="position: fixed; top: 15px; right: 15px;"></div>
    </div>
  </body>
</html>